version: '3.3'
services:
    api:
        build: ./out/python-ts-iot
        image: "myapi"
        hostname: "myapi"
        ports:
            - "8080:8080"
        networks:
            - iot-labs
        labels:
            NAME: "myapi"
networks:
    iot-labs:
        external: true
