version: '3.3'
services:
    ftp:
        image: "fauria/vsftpd"
        hostname: "ftp"
        environment:
            FTP_USER: "user"
            FTP_PASS: "password"
            LOG_STDOUT: "YES"
        ports:
            - "21:21"
        volumes:
            - "./ftp:/home/vsftpd"
        networks:
            - iot-labs
        labels:
            NAME: "ftp"
        privileged: true
        restart: always
networks:
    iot-labs:
        external: true
