version: '3.3'
services:
    nifi:
        image: "apache/nifi:1.9.2"
        hostname: "nifi"
        environment:
            NIFI_WEB_HTTP_PORT: "8080"
        ports:
            - "8083:8080"
        networks:
            - iot-labs
        labels:
            NAME: "nifi"
networks:
    iot-labs:
        external: true
